name: Build gRPC Libraries

on:
  workflow_dispatch:
  push:
    paths:
      - 'Source/ProtoBridgeThirdParty/scripts/**'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Enable long paths for git
        run: git config --global core.longpaths true

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install NASM
        run: choco install nasm

      - name: Setup MSVC Environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Run Build Script
        shell: pwsh
        run: |
          ./Source/ProtoBridgeThirdParty/scripts/build_win64.ps1

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ProtoBridge-Win64
          path: |
            bin/Win64
            lib/Win64
            includes
          retention-days: 1

  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake git nasm ninja-build autoconf libtool pkg-config

      - name: Run Build Script
        run: |
          sed -i 's/\r$//' ./Source/ProtoBridgeThirdParty/scripts/build_linux.sh
          chmod +x ./Source/ProtoBridgeThirdParty/scripts/build_linux.sh
          ./Source/ProtoBridgeThirdParty/scripts/build_linux.sh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ProtoBridge-Linux
          path: |
            bin/Linux
            lib/Linux
            includes
          retention-days: 1

  build-android:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake git ninja-build

      - name: Setup Android NDK
        id: setup-ndk
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26d

      - name: Run Build Script
        run: |
          sed -i 's/\r$//' ./Source/ProtoBridgeThirdParty/scripts/build_android.sh
          chmod +x ./Source/ProtoBridgeThirdParty/scripts/build_android.sh
          ./Source/ProtoBridgeThirdParty/scripts/build_android.sh
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ProtoBridge-Android
          path: |
            lib/Android
            includes
          retention-days: 1
